name: tezlapen_v2
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  any_link_preview: ^3.0.1
  bloc: ^8.1.2
  chewie: ^1.7.4
  cloud_firestore: ^4.15.3
  confetti: ^0.7.0
  expandable_text: ^2.3.0
  file_picker: ^6.1.1
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  firebase_ui_auth: ^1.12.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_link_previewer: ^3.2.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  provider: ^6.1.1
  shimmer: ^3.0.0
  url_launcher: ^6.2.4
  uuid: ^4.3.3
  video_player: ^2.8.2
  vrouter: ^1.2.1

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
