// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcQjwBOaB1TKxAZPYsgBOl0olfsA62kpI',
    appId: '1:295129606081:web:3ddfddd29de7f436413140',
    messagingSenderId: '295129606081',
    projectId: 'tezlapen',
    authDomain: 'tezlapen.firebaseapp.com',
    storageBucket: 'tezlapen.appspot.com',
    measurementId: 'G-4K2PDGJDVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7UWwyic4JzzGn0_TS8NqvfXMHQBClcbI',
    appId: '1:295129606081:android:0dcbc26d5be8dce9413140',
    messagingSenderId: '295129606081',
    projectId: 'tezlapen',
    storageBucket: 'tezlapen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2J-5ct989gyL7CyeqVfjVROt5VlLr9HE',
    appId: '1:295129606081:ios:2875f7a903cb7bb9413140',
    messagingSenderId: '295129606081',
    projectId: 'tezlapen',
    storageBucket: 'tezlapen.appspot.com',
    iosBundleId: 'com.example.verygoodcore.tezlapen-v2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2J-5ct989gyL7CyeqVfjVROt5VlLr9HE',
    appId: '1:295129606081:ios:ebaaca37c4f2d955413140',
    messagingSenderId: '295129606081',
    projectId: 'tezlapen',
    storageBucket: 'tezlapen.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
